# Generated by Django 4.2.7 on 2023-12-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_alter_envio_destino_alter_envio_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plasticparts',
            old_name='carcasa_color_amarillo',
            new_name='caja_de_airpods',
        ),
        migrations.RenameField(
            model_name='plasticparts',
            old_name='carcasa_color_azul',
            new_name='caja_de_cable',
        ),
        migrations.RenameField(
            model_name='plasticparts',
            old_name='carcasa_color_cyan',
            new_name='caja_de_cargador',
        ),
        migrations.RenameField(
            model_name='plasticparts',
            old_name='carcasa_color_morado',
            new_name='caja_de_telefono',
        ),
        migrations.RenameField(
            model_name='plasticparts',
            old_name='carcasa_color_rosa',
            new_name='plastico_para_carcasas_de_airpods',
        ),
        migrations.RenameField(
            model_name='plasticparts',
            old_name='carcasa_color_verde',
            new_name='plastico_para_carcasas_de_iphone',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='carcasa_color_amarillo',
            new_name='caja_de_airpods',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='carcasa_color_azul',
            new_name='caja_de_cable',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='carcasa_color_cyan',
            new_name='caja_de_cargador',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='carcasa_color_morado',
            new_name='caja_de_telefono',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='carcasa_color_rosa',
            new_name='plastico_para_carcasas_de_airpods',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='carcasa_color_verde',
            new_name='plastico_para_carcasas_de_iphone',
        ),
    ]
